name: weather_app
description: "Flutter Weather App"


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.6.1







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  bloc: ^9.0.0
  dio: ^5.8.0+1
  lottie: ^3.3.1
  geolocator: ^13.0.3
  iconsax: ^0.0.8
  another_flushbar: ^1.12.30
  fluttertoast: ^8.2.10
  equatable: ^2.0.7
  get_it: ^8.0.3
  permission_handler: ^11.4.0
  jiffy: ^6.3.2
  animated_text_kit: ^4.2.3
  weather_animation: ^1.1.2
  device_preview: ^1.2.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/animations/
    - assets/images/


  fonts:
#    - family: MaterialIcons
#      fonts:
#        - asset: build/web/assets/fonts/MaterialIcons-Regular.otf

#    - family: MaterialIcons
#      fonts:
#        - asset: fonts/MaterialIcons-Regular.otf
    - family: Lita-Regular
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
    - family: Ex-Bold
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
    - family: Ex-Medium
      fonts:
        - asset: assets/fonts/Exo2-Medium.ttf
    - family: Ex-Regular
      fonts:
        - asset: assets/fonts/Exo2-Regular.ttf



  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
